// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: routerchain/crosschain/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgCrosschainRequest struct {
	Orchestrator    string `protobuf:"bytes,1,opt,name=orchestrator,proto3" json:"orchestrator,omitempty"`
	SrcchainId      string `protobuf:"bytes,2,opt,name=srcchainId,proto3" json:"srcchainId,omitempty"`
	EventNonce      uint64 `protobuf:"varint,3,opt,name=eventNonce,proto3" json:"eventNonce,omitempty"`
	BlockHeight     uint64 `protobuf:"varint,4,opt,name=blockHeight,proto3" json:"blockHeight,omitempty"`
	SourceTxHash    string `protobuf:"bytes,5,opt,name=sourceTxHash,proto3" json:"sourceTxHash,omitempty"`
	SrcTimestamp    uint64 `protobuf:"varint,6,opt,name=srcTimestamp,proto3" json:"srcTimestamp,omitempty"`
	SrcTxOrigin     string `protobuf:"bytes,7,opt,name=srcTxOrigin,proto3" json:"srcTxOrigin,omitempty"`
	RouteAmount     string `protobuf:"bytes,8,opt,name=routeAmount,proto3" json:"routeAmount,omitempty"`
	RouteRecipient  string `protobuf:"bytes,9,opt,name=routeRecipient,proto3" json:"routeRecipient,omitempty"`
	DestChainId     string `protobuf:"bytes,10,opt,name=destChainId,proto3" json:"destChainId,omitempty"`
	RequestSender   string `protobuf:"bytes,11,opt,name=requestSender,proto3" json:"requestSender,omitempty"`
	RequestMetadata []byte `protobuf:"bytes,12,opt,name=request_metadata,json=requestMetadata,proto3" json:"request_metadata,omitempty"`
	RequestPayload  []byte `protobuf:"bytes,13,opt,name=request_payload,json=requestPayload,proto3" json:"request_payload,omitempty"`
	RelayerFee      string `protobuf:"bytes,14,opt,name=relayerFee,proto3" json:"relayerFee,omitempty"`
}

func (m *MsgCrosschainRequest) Reset()         { *m = MsgCrosschainRequest{} }
func (m *MsgCrosschainRequest) String() string { return proto.CompactTextString(m) }
func (*MsgCrosschainRequest) ProtoMessage()    {}
func (*MsgCrosschainRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ef225a639df9939d, []int{0}
}
func (m *MsgCrosschainRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCrosschainRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCrosschainRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCrosschainRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCrosschainRequest.Merge(m, src)
}
func (m *MsgCrosschainRequest) XXX_Size() int {
	return m.Size()
}
func (m *MsgCrosschainRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCrosschainRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCrosschainRequest proto.InternalMessageInfo

func (m *MsgCrosschainRequest) GetOrchestrator() string {
	if m != nil {
		return m.Orchestrator
	}
	return ""
}

func (m *MsgCrosschainRequest) GetSrcchainId() string {
	if m != nil {
		return m.SrcchainId
	}
	return ""
}

func (m *MsgCrosschainRequest) GetEventNonce() uint64 {
	if m != nil {
		return m.EventNonce
	}
	return 0
}

func (m *MsgCrosschainRequest) GetBlockHeight() uint64 {
	if m != nil {
		return m.BlockHeight
	}
	return 0
}

func (m *MsgCrosschainRequest) GetSourceTxHash() string {
	if m != nil {
		return m.SourceTxHash
	}
	return ""
}

func (m *MsgCrosschainRequest) GetSrcTimestamp() uint64 {
	if m != nil {
		return m.SrcTimestamp
	}
	return 0
}

func (m *MsgCrosschainRequest) GetSrcTxOrigin() string {
	if m != nil {
		return m.SrcTxOrigin
	}
	return ""
}

func (m *MsgCrosschainRequest) GetRouteAmount() string {
	if m != nil {
		return m.RouteAmount
	}
	return ""
}

func (m *MsgCrosschainRequest) GetRouteRecipient() string {
	if m != nil {
		return m.RouteRecipient
	}
	return ""
}

func (m *MsgCrosschainRequest) GetDestChainId() string {
	if m != nil {
		return m.DestChainId
	}
	return ""
}

func (m *MsgCrosschainRequest) GetRequestSender() string {
	if m != nil {
		return m.RequestSender
	}
	return ""
}

func (m *MsgCrosschainRequest) GetRequestMetadata() []byte {
	if m != nil {
		return m.RequestMetadata
	}
	return nil
}

func (m *MsgCrosschainRequest) GetRequestPayload() []byte {
	if m != nil {
		return m.RequestPayload
	}
	return nil
}

func (m *MsgCrosschainRequest) GetRelayerFee() string {
	if m != nil {
		return m.RelayerFee
	}
	return ""
}

type MsgCrosschainRequestResponse struct {
}

func (m *MsgCrosschainRequestResponse) Reset()         { *m = MsgCrosschainRequestResponse{} }
func (m *MsgCrosschainRequestResponse) String() string { return proto.CompactTextString(m) }
func (*MsgCrosschainRequestResponse) ProtoMessage()    {}
func (*MsgCrosschainRequestResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ef225a639df9939d, []int{1}
}
func (m *MsgCrosschainRequestResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCrosschainRequestResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCrosschainRequestResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCrosschainRequestResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCrosschainRequestResponse.Merge(m, src)
}
func (m *MsgCrosschainRequestResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgCrosschainRequestResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCrosschainRequestResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCrosschainRequestResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgCrosschainRequest)(nil), "routerprotocol.routerchain.crosschain.MsgCrosschainRequest")
	proto.RegisterType((*MsgCrosschainRequestResponse)(nil), "routerprotocol.routerchain.crosschain.MsgCrosschainRequestResponse")
}

func init() { proto.RegisterFile("routerchain/crosschain/tx.proto", fileDescriptor_ef225a639df9939d) }

var fileDescriptor_ef225a639df9939d = []byte{
	// 445 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x93, 0x3f, 0x8f, 0xd3, 0x30,
	0x14, 0xc0, 0x6b, 0xae, 0x1c, 0x9c, 0xaf, 0x57, 0xc0, 0x62, 0xb0, 0x10, 0x32, 0x55, 0xc5, 0x9f,
	0x32, 0x90, 0x93, 0x60, 0x83, 0x09, 0x2a, 0xa1, 0x63, 0x28, 0xa0, 0xd0, 0x89, 0xe5, 0xe4, 0x3a,
	0x4f, 0x89, 0x45, 0x63, 0x07, 0xdb, 0x41, 0xed, 0x77, 0x60, 0x60, 0x61, 0xe4, 0xfb, 0x30, 0xde,
	0xc8, 0x88, 0xda, 0x2f, 0x82, 0x62, 0xa7, 0x9c, 0x03, 0x37, 0x20, 0xb1, 0xe5, 0xfd, 0xf2, 0xf3,
	0x7b, 0x4f, 0xcf, 0xcf, 0xf8, 0x8e, 0xd1, 0xb5, 0x03, 0x23, 0x0a, 0x2e, 0xd5, 0xb1, 0x30, 0xda,
	0xda, 0xf0, 0xe9, 0x56, 0x49, 0x65, 0xb4, 0xd3, 0xe4, 0x5e, 0x10, 0x7c, 0x20, 0xf4, 0x32, 0x89,
	0xfc, 0xe4, 0xdc, 0x1f, 0x7f, 0xee, 0xe3, 0x9b, 0x33, 0x9b, 0x4f, 0x7f, 0x93, 0x14, 0x3e, 0xd6,
	0x60, 0x1d, 0x19, 0xe3, 0x81, 0x36, 0xa2, 0x00, 0xeb, 0x0c, 0x77, 0xda, 0x50, 0x34, 0x42, 0x93,
	0x83, 0xb4, 0xc3, 0x08, 0xc3, 0xd8, 0x1a, 0xe1, 0x8f, 0xbd, 0xca, 0xe8, 0x25, 0x6f, 0x44, 0xa4,
	0xf9, 0x0f, 0x9f, 0x40, 0xb9, 0xd7, 0x5a, 0x09, 0xa0, 0x7b, 0x23, 0x34, 0xe9, 0xa7, 0x11, 0x21,
	0x23, 0x7c, 0xb8, 0x58, 0x6a, 0xf1, 0xe1, 0x04, 0x64, 0x5e, 0x38, 0xda, 0xf7, 0x42, 0x8c, 0x9a,
	0x2e, 0xac, 0xae, 0x8d, 0x80, 0xf9, 0xea, 0x84, 0xdb, 0x82, 0x5e, 0x0e, 0x5d, 0xc4, 0xcc, 0x3b,
	0x46, 0xcc, 0x65, 0x09, 0xd6, 0xf1, 0xb2, 0xa2, 0xfb, 0x3e, 0x4d, 0x87, 0x35, 0x95, 0x9a, 0x78,
	0xf5, 0xc6, 0xc8, 0x5c, 0x2a, 0x7a, 0xc5, 0xa7, 0x89, 0x51, 0x63, 0xf8, 0x11, 0x3d, 0x2f, 0x75,
	0xad, 0x1c, 0xbd, 0x1a, 0x8c, 0x08, 0x91, 0xfb, 0x78, 0xe8, 0xc3, 0x14, 0x84, 0xac, 0x24, 0x28,
	0x47, 0x0f, 0xbc, 0xf4, 0x07, 0x6d, 0x32, 0x65, 0x60, 0xdd, 0xb4, 0x1d, 0x0b, 0x0e, 0x99, 0x22,
	0x44, 0xee, 0xe2, 0x23, 0x13, 0xc6, 0xfc, 0x0e, 0x54, 0x06, 0x86, 0x1e, 0x7a, 0xa7, 0x0b, 0xc9,
	0x43, 0x7c, 0xbd, 0x05, 0xa7, 0x25, 0x38, 0x9e, 0x71, 0xc7, 0xe9, 0x60, 0x84, 0x26, 0x83, 0xf4,
	0x5a, 0xcb, 0x67, 0x2d, 0x26, 0x0f, 0xf0, 0x0e, 0x9d, 0x56, 0x7c, 0xbd, 0xd4, 0x3c, 0xa3, 0x47,
	0xde, 0x1c, 0xb6, 0xf8, 0x6d, 0xa0, 0xcd, 0x8d, 0x18, 0x58, 0xf2, 0x35, 0x98, 0x97, 0x00, 0x74,
	0x18, 0x6e, 0xec, 0x9c, 0x8c, 0x19, 0xbe, 0x7d, 0xd1, 0x36, 0xa4, 0x60, 0x2b, 0xad, 0x2c, 0x3c,
	0xfe, 0x86, 0xf0, 0xde, 0xcc, 0xe6, 0xe4, 0x2b, 0xc2, 0x37, 0xfe, 0xde, 0x99, 0x67, 0xc9, 0x3f,
	0x2d, 0x5d, 0x72, 0x51, 0x89, 0x5b, 0xd3, 0xff, 0x38, 0xbc, 0xeb, 0xef, 0xc5, 0xfc, 0xfb, 0x86,
	0xa1, 0xb3, 0x0d, 0x43, 0x3f, 0x37, 0x0c, 0x7d, 0xd9, 0xb2, 0xde, 0xd9, 0x96, 0xf5, 0x7e, 0x6c,
	0x59, 0xef, 0xfd, 0xd3, 0x5c, 0xba, 0xa2, 0x5e, 0x24, 0x42, 0x97, 0xc7, 0x21, 0xf3, 0xa3, 0x5d,
	0xa5, 0x5d, 0x1c, 0x5e, 0xd0, 0xaa, 0xf3, 0x9c, 0xd6, 0x15, 0xd8, 0xc5, 0xbe, 0x37, 0x9f, 0xfc,
	0x0a, 0x00, 0x00, 0xff, 0xff, 0x12, 0x13, 0xb1, 0xa1, 0x75, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	CrosschainRequest(ctx context.Context, in *MsgCrosschainRequest, opts ...grpc.CallOption) (*MsgCrosschainRequestResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) CrosschainRequest(ctx context.Context, in *MsgCrosschainRequest, opts ...grpc.CallOption) (*MsgCrosschainRequestResponse, error) {
	out := new(MsgCrosschainRequestResponse)
	err := c.cc.Invoke(ctx, "/routerprotocol.routerchain.crosschain.Msg/CrosschainRequest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	CrosschainRequest(context.Context, *MsgCrosschainRequest) (*MsgCrosschainRequestResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) CrosschainRequest(ctx context.Context, req *MsgCrosschainRequest) (*MsgCrosschainRequestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CrosschainRequest not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_CrosschainRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCrosschainRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CrosschainRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/routerprotocol.routerchain.crosschain.Msg/CrosschainRequest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CrosschainRequest(ctx, req.(*MsgCrosschainRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "routerprotocol.routerchain.crosschain.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CrosschainRequest",
			Handler:    _Msg_CrosschainRequest_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "routerchain/crosschain/tx.proto",
}

func (m *MsgCrosschainRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCrosschainRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCrosschainRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.RelayerFee) > 0 {
		i -= len(m.RelayerFee)
		copy(dAtA[i:], m.RelayerFee)
		i = encodeVarintTx(dAtA, i, uint64(len(m.RelayerFee)))
		i--
		dAtA[i] = 0x72
	}
	if len(m.RequestPayload) > 0 {
		i -= len(m.RequestPayload)
		copy(dAtA[i:], m.RequestPayload)
		i = encodeVarintTx(dAtA, i, uint64(len(m.RequestPayload)))
		i--
		dAtA[i] = 0x6a
	}
	if len(m.RequestMetadata) > 0 {
		i -= len(m.RequestMetadata)
		copy(dAtA[i:], m.RequestMetadata)
		i = encodeVarintTx(dAtA, i, uint64(len(m.RequestMetadata)))
		i--
		dAtA[i] = 0x62
	}
	if len(m.RequestSender) > 0 {
		i -= len(m.RequestSender)
		copy(dAtA[i:], m.RequestSender)
		i = encodeVarintTx(dAtA, i, uint64(len(m.RequestSender)))
		i--
		dAtA[i] = 0x5a
	}
	if len(m.DestChainId) > 0 {
		i -= len(m.DestChainId)
		copy(dAtA[i:], m.DestChainId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.DestChainId)))
		i--
		dAtA[i] = 0x52
	}
	if len(m.RouteRecipient) > 0 {
		i -= len(m.RouteRecipient)
		copy(dAtA[i:], m.RouteRecipient)
		i = encodeVarintTx(dAtA, i, uint64(len(m.RouteRecipient)))
		i--
		dAtA[i] = 0x4a
	}
	if len(m.RouteAmount) > 0 {
		i -= len(m.RouteAmount)
		copy(dAtA[i:], m.RouteAmount)
		i = encodeVarintTx(dAtA, i, uint64(len(m.RouteAmount)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.SrcTxOrigin) > 0 {
		i -= len(m.SrcTxOrigin)
		copy(dAtA[i:], m.SrcTxOrigin)
		i = encodeVarintTx(dAtA, i, uint64(len(m.SrcTxOrigin)))
		i--
		dAtA[i] = 0x3a
	}
	if m.SrcTimestamp != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.SrcTimestamp))
		i--
		dAtA[i] = 0x30
	}
	if len(m.SourceTxHash) > 0 {
		i -= len(m.SourceTxHash)
		copy(dAtA[i:], m.SourceTxHash)
		i = encodeVarintTx(dAtA, i, uint64(len(m.SourceTxHash)))
		i--
		dAtA[i] = 0x2a
	}
	if m.BlockHeight != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.BlockHeight))
		i--
		dAtA[i] = 0x20
	}
	if m.EventNonce != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.EventNonce))
		i--
		dAtA[i] = 0x18
	}
	if len(m.SrcchainId) > 0 {
		i -= len(m.SrcchainId)
		copy(dAtA[i:], m.SrcchainId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.SrcchainId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Orchestrator) > 0 {
		i -= len(m.Orchestrator)
		copy(dAtA[i:], m.Orchestrator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Orchestrator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgCrosschainRequestResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCrosschainRequestResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCrosschainRequestResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgCrosschainRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Orchestrator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.SrcchainId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.EventNonce != 0 {
		n += 1 + sovTx(uint64(m.EventNonce))
	}
	if m.BlockHeight != 0 {
		n += 1 + sovTx(uint64(m.BlockHeight))
	}
	l = len(m.SourceTxHash)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.SrcTimestamp != 0 {
		n += 1 + sovTx(uint64(m.SrcTimestamp))
	}
	l = len(m.SrcTxOrigin)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.RouteAmount)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.RouteRecipient)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.DestChainId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.RequestSender)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.RequestMetadata)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.RequestPayload)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.RelayerFee)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgCrosschainRequestResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgCrosschainRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCrosschainRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCrosschainRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Orchestrator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Orchestrator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SrcchainId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SrcchainId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EventNonce", wireType)
			}
			m.EventNonce = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EventNonce |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlockHeight", wireType)
			}
			m.BlockHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BlockHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SourceTxHash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SourceTxHash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SrcTimestamp", wireType)
			}
			m.SrcTimestamp = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SrcTimestamp |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SrcTxOrigin", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SrcTxOrigin = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RouteAmount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RouteAmount = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RouteRecipient", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RouteRecipient = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DestChainId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DestChainId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RequestSender", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RequestSender = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RequestMetadata", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RequestMetadata = append(m.RequestMetadata[:0], dAtA[iNdEx:postIndex]...)
			if m.RequestMetadata == nil {
				m.RequestMetadata = []byte{}
			}
			iNdEx = postIndex
		case 13:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RequestPayload", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RequestPayload = append(m.RequestPayload[:0], dAtA[iNdEx:postIndex]...)
			if m.RequestPayload == nil {
				m.RequestPayload = []byte{}
			}
			iNdEx = postIndex
		case 14:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RelayerFee", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RelayerFee = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCrosschainRequestResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCrosschainRequestResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCrosschainRequestResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
