// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: routerchain/voyager/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	types "github.com/router-protocol/sdk-go/routerchain/multichain/types"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgFundsDeposited struct {
	Orchestrator  string          `protobuf:"bytes,1,opt,name=orchestrator,proto3" json:"orchestrator,omitempty"`
	SrcChainId    string          `protobuf:"bytes,2,opt,name=srcChainId,proto3" json:"srcChainId,omitempty"`
	SrcChainType  types.ChainType `protobuf:"varint,3,opt,name=srcChainType,proto3,enum=routerprotocol.routerchain.multichain.ChainType" json:"srcChainType,omitempty"`
	SrcTxHash     string          `protobuf:"bytes,4,opt,name=srcTxHash,proto3" json:"srcTxHash,omitempty"`
	SrcTimestamp  uint64          `protobuf:"varint,5,opt,name=srcTimestamp,proto3" json:"srcTimestamp,omitempty"`
	Contract      string          `protobuf:"bytes,6,opt,name=contract,proto3" json:"contract,omitempty"`
	DepositId     uint64          `protobuf:"varint,7,opt,name=deposit_id,json=depositId,proto3" json:"deposit_id,omitempty"`
	BlockHeight   uint64          `protobuf:"varint,8,opt,name=blockHeight,proto3" json:"blockHeight,omitempty"`
	DestChainId   string          `protobuf:"bytes,9,opt,name=destChainId,proto3" json:"destChainId,omitempty"`
	DestChainType types.ChainType `protobuf:"varint,10,opt,name=destChainType,proto3,enum=routerprotocol.routerchain.multichain.ChainType" json:"destChainType,omitempty"`
	Amount        uint64          `protobuf:"varint,11,opt,name=amount,proto3" json:"amount,omitempty"`
	RelayerFees   uint64          `protobuf:"varint,12,opt,name=relayerFees,proto3" json:"relayerFees,omitempty"`
	SrcToken      string          `protobuf:"bytes,13,opt,name=srcToken,proto3" json:"srcToken,omitempty"`
	Recipient     string          `protobuf:"bytes,14,opt,name=recipient,proto3" json:"recipient,omitempty"`
	Depositor     string          `protobuf:"bytes,15,opt,name=depositor,proto3" json:"depositor,omitempty"`
}

func (m *MsgFundsDeposited) Reset()         { *m = MsgFundsDeposited{} }
func (m *MsgFundsDeposited) String() string { return proto.CompactTextString(m) }
func (*MsgFundsDeposited) ProtoMessage()    {}
func (*MsgFundsDeposited) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c9d038a907e69fe, []int{0}
}
func (m *MsgFundsDeposited) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgFundsDeposited) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgFundsDeposited.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgFundsDeposited) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgFundsDeposited.Merge(m, src)
}
func (m *MsgFundsDeposited) XXX_Size() int {
	return m.Size()
}
func (m *MsgFundsDeposited) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgFundsDeposited.DiscardUnknown(m)
}

var xxx_messageInfo_MsgFundsDeposited proto.InternalMessageInfo

func (m *MsgFundsDeposited) GetOrchestrator() string {
	if m != nil {
		return m.Orchestrator
	}
	return ""
}

func (m *MsgFundsDeposited) GetSrcChainId() string {
	if m != nil {
		return m.SrcChainId
	}
	return ""
}

func (m *MsgFundsDeposited) GetSrcChainType() types.ChainType {
	if m != nil {
		return m.SrcChainType
	}
	return types.CHAIN_TYPE_NONE
}

func (m *MsgFundsDeposited) GetSrcTxHash() string {
	if m != nil {
		return m.SrcTxHash
	}
	return ""
}

func (m *MsgFundsDeposited) GetSrcTimestamp() uint64 {
	if m != nil {
		return m.SrcTimestamp
	}
	return 0
}

func (m *MsgFundsDeposited) GetContract() string {
	if m != nil {
		return m.Contract
	}
	return ""
}

func (m *MsgFundsDeposited) GetDepositId() uint64 {
	if m != nil {
		return m.DepositId
	}
	return 0
}

func (m *MsgFundsDeposited) GetBlockHeight() uint64 {
	if m != nil {
		return m.BlockHeight
	}
	return 0
}

func (m *MsgFundsDeposited) GetDestChainId() string {
	if m != nil {
		return m.DestChainId
	}
	return ""
}

func (m *MsgFundsDeposited) GetDestChainType() types.ChainType {
	if m != nil {
		return m.DestChainType
	}
	return types.CHAIN_TYPE_NONE
}

func (m *MsgFundsDeposited) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *MsgFundsDeposited) GetRelayerFees() uint64 {
	if m != nil {
		return m.RelayerFees
	}
	return 0
}

func (m *MsgFundsDeposited) GetSrcToken() string {
	if m != nil {
		return m.SrcToken
	}
	return ""
}

func (m *MsgFundsDeposited) GetRecipient() string {
	if m != nil {
		return m.Recipient
	}
	return ""
}

func (m *MsgFundsDeposited) GetDepositor() string {
	if m != nil {
		return m.Depositor
	}
	return ""
}

type MsgFundsDepositedResponse struct {
}

func (m *MsgFundsDepositedResponse) Reset()         { *m = MsgFundsDepositedResponse{} }
func (m *MsgFundsDepositedResponse) String() string { return proto.CompactTextString(m) }
func (*MsgFundsDepositedResponse) ProtoMessage()    {}
func (*MsgFundsDepositedResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c9d038a907e69fe, []int{1}
}
func (m *MsgFundsDepositedResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgFundsDepositedResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgFundsDepositedResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgFundsDepositedResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgFundsDepositedResponse.Merge(m, src)
}
func (m *MsgFundsDepositedResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgFundsDepositedResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgFundsDepositedResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgFundsDepositedResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgFundsDeposited)(nil), "routerprotocol.routerchain.voyager.MsgFundsDeposited")
	proto.RegisterType((*MsgFundsDepositedResponse)(nil), "routerprotocol.routerchain.voyager.MsgFundsDepositedResponse")
}

func init() { proto.RegisterFile("routerchain/voyager/tx.proto", fileDescriptor_8c9d038a907e69fe) }

var fileDescriptor_8c9d038a907e69fe = []byte{
	// 497 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x53, 0x41, 0x6f, 0xd3, 0x30,
	0x14, 0x6e, 0x58, 0x29, 0xab, 0xd7, 0x15, 0x61, 0x21, 0x64, 0xba, 0x11, 0x55, 0x3d, 0xf5, 0x42,
	0xc2, 0x86, 0x10, 0x27, 0x2e, 0x80, 0xa6, 0xed, 0xb0, 0x03, 0x55, 0xc5, 0x81, 0xcb, 0xe4, 0x3a,
	0x4f, 0xa9, 0xb5, 0x26, 0x2f, 0xb2, 0xdd, 0xa9, 0xfd, 0x03, 0x1c, 0x11, 0x3f, 0x8b, 0xe3, 0x8e,
	0x3b, 0xa2, 0xf6, 0x8f, 0x20, 0xdb, 0x4d, 0x9a, 0x32, 0x09, 0xa4, 0x5d, 0xa2, 0x7c, 0xdf, 0x7b,
	0xef, 0xf3, 0xe7, 0x4f, 0x7e, 0xe4, 0x58, 0xe1, 0xdc, 0x80, 0x12, 0x53, 0x2e, 0xf3, 0xf8, 0x06,
	0x97, 0x3c, 0x05, 0x15, 0x9b, 0x45, 0x54, 0x28, 0x34, 0x48, 0x07, 0xbe, 0xea, 0x80, 0xc0, 0x59,
	0x54, 0x6b, 0x8e, 0x36, 0xcd, 0xbd, 0xa3, 0x6c, 0x3e, 0x33, 0xd2, 0x0b, 0xb8, 0xef, 0x95, 0x59,
	0x16, 0xe0, 0x05, 0x7a, 0xa1, 0x40, 0x9d, 0xa1, 0x8e, 0x27, 0x5c, 0x43, 0x7c, 0x73, 0x32, 0x01,
	0xc3, 0x4f, 0x62, 0x81, 0x32, 0xdf, 0xd4, 0x9f, 0xa7, 0x98, 0xa2, 0xfb, 0x8d, 0xed, 0x9f, 0x67,
	0x07, 0x77, 0x4d, 0xf2, 0xec, 0x52, 0xa7, 0x67, 0xf3, 0x3c, 0xd1, 0x9f, 0xa1, 0x40, 0x2d, 0x0d,
	0x24, 0x74, 0x40, 0x3a, 0xa8, 0xc4, 0x14, 0xb4, 0x51, 0xdc, 0xa0, 0x62, 0x41, 0x3f, 0x18, 0xb6,
	0x47, 0x3b, 0x1c, 0x0d, 0x09, 0xd1, 0x4a, 0x7c, 0xb2, 0x36, 0x2e, 0x12, 0xf6, 0xc8, 0x75, 0xd4,
	0x18, 0x3a, 0x26, 0x9d, 0x12, 0x8d, 0x97, 0x05, 0xb0, 0xbd, 0x7e, 0x30, 0xec, 0x9e, 0xbe, 0x89,
	0xfe, 0x71, 0xcf, 0xed, 0xf5, 0xa2, 0x6a, 0x6e, 0xb4, 0xa3, 0x42, 0x8f, 0x49, 0x5b, 0x2b, 0x31,
	0x5e, 0x9c, 0x73, 0x3d, 0x65, 0x4d, 0x77, 0xe8, 0x96, 0xb0, 0xbe, 0x2d, 0x90, 0x19, 0x68, 0xc3,
	0xb3, 0x82, 0x3d, 0xee, 0x07, 0xc3, 0xe6, 0x68, 0x87, 0xa3, 0x3d, 0xb2, 0x2f, 0x30, 0x37, 0x8a,
	0x0b, 0xc3, 0x5a, 0x4e, 0xa0, 0xc2, 0xf4, 0x15, 0x21, 0x89, 0x0f, 0xe1, 0x4a, 0x26, 0xec, 0x89,
	0x9b, 0x6e, 0x6f, 0x98, 0x8b, 0x84, 0xf6, 0xc9, 0xc1, 0x64, 0x86, 0xe2, 0xfa, 0x1c, 0x64, 0x3a,
	0x35, 0x6c, 0xdf, 0xd5, 0xeb, 0x94, 0xed, 0x48, 0x40, 0x9b, 0x32, 0x95, 0xb6, 0xd3, 0xaf, 0x53,
	0xf4, 0x2b, 0x39, 0xac, 0xa0, 0xcb, 0x85, 0x3c, 0x30, 0x97, 0x5d, 0x19, 0xfa, 0x82, 0xb4, 0x78,
	0x86, 0xf3, 0xdc, 0xb0, 0x03, 0x67, 0x6b, 0x83, 0xac, 0x23, 0x05, 0x33, 0xbe, 0x04, 0x75, 0x06,
	0xa0, 0x59, 0xc7, 0x7b, 0xae, 0x51, 0x36, 0x10, 0x1b, 0x10, 0x5e, 0x43, 0xce, 0x0e, 0x7d, 0x20,
	0x25, 0xb6, 0x71, 0x2b, 0x10, 0xb2, 0x90, 0x90, 0x1b, 0xd6, 0xf5, 0x71, 0x57, 0x84, 0xad, 0x6e,
	0xc2, 0x41, 0xc5, 0x9e, 0xfa, 0x6a, 0x45, 0x0c, 0x8e, 0xc8, 0xcb, 0x7b, 0x2f, 0x6b, 0x04, 0xba,
	0xc0, 0x5c, 0xc3, 0xe9, 0x8f, 0x80, 0xec, 0x5d, 0xea, 0x94, 0x7e, 0x0f, 0x48, 0xf7, 0xaf, 0xc7,
	0xf7, 0x2e, 0xfa, 0xff, 0x2a, 0x44, 0xf7, 0x94, 0x7b, 0x1f, 0x1e, 0x34, 0x56, 0x1a, 0xfa, 0xf8,
	0xe5, 0xd7, 0x2a, 0x0c, 0x6e, 0x57, 0x61, 0xf0, 0x7b, 0x15, 0x06, 0x3f, 0xd7, 0x61, 0xe3, 0x76,
	0x1d, 0x36, 0xee, 0xd6, 0x61, 0xe3, 0xdb, 0xfb, 0x54, 0x9a, 0xe9, 0x7c, 0x12, 0x09, 0xcc, 0x62,
	0xaf, 0xf9, 0xba, 0x3c, 0xa3, 0xc4, 0x7e, 0x25, 0x17, 0xdb, 0xad, 0x5e, 0x16, 0xa0, 0x27, 0x2d,
	0xd7, 0xf6, 0xf6, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x02, 0x4a, 0x49, 0x64, 0xf9, 0x03, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	FundsDeposited(ctx context.Context, in *MsgFundsDeposited, opts ...grpc.CallOption) (*MsgFundsDepositedResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) FundsDeposited(ctx context.Context, in *MsgFundsDeposited, opts ...grpc.CallOption) (*MsgFundsDepositedResponse, error) {
	out := new(MsgFundsDepositedResponse)
	err := c.cc.Invoke(ctx, "/routerprotocol.routerchain.voyager.Msg/FundsDeposited", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	FundsDeposited(context.Context, *MsgFundsDeposited) (*MsgFundsDepositedResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) FundsDeposited(ctx context.Context, req *MsgFundsDeposited) (*MsgFundsDepositedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FundsDeposited not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_FundsDeposited_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgFundsDeposited)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).FundsDeposited(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/routerprotocol.routerchain.voyager.Msg/FundsDeposited",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).FundsDeposited(ctx, req.(*MsgFundsDeposited))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "routerprotocol.routerchain.voyager.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FundsDeposited",
			Handler:    _Msg_FundsDeposited_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "routerchain/voyager/tx.proto",
}

func (m *MsgFundsDeposited) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgFundsDeposited) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgFundsDeposited) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Depositor) > 0 {
		i -= len(m.Depositor)
		copy(dAtA[i:], m.Depositor)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Depositor)))
		i--
		dAtA[i] = 0x7a
	}
	if len(m.Recipient) > 0 {
		i -= len(m.Recipient)
		copy(dAtA[i:], m.Recipient)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Recipient)))
		i--
		dAtA[i] = 0x72
	}
	if len(m.SrcToken) > 0 {
		i -= len(m.SrcToken)
		copy(dAtA[i:], m.SrcToken)
		i = encodeVarintTx(dAtA, i, uint64(len(m.SrcToken)))
		i--
		dAtA[i] = 0x6a
	}
	if m.RelayerFees != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.RelayerFees))
		i--
		dAtA[i] = 0x60
	}
	if m.Amount != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Amount))
		i--
		dAtA[i] = 0x58
	}
	if m.DestChainType != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.DestChainType))
		i--
		dAtA[i] = 0x50
	}
	if len(m.DestChainId) > 0 {
		i -= len(m.DestChainId)
		copy(dAtA[i:], m.DestChainId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.DestChainId)))
		i--
		dAtA[i] = 0x4a
	}
	if m.BlockHeight != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.BlockHeight))
		i--
		dAtA[i] = 0x40
	}
	if m.DepositId != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.DepositId))
		i--
		dAtA[i] = 0x38
	}
	if len(m.Contract) > 0 {
		i -= len(m.Contract)
		copy(dAtA[i:], m.Contract)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Contract)))
		i--
		dAtA[i] = 0x32
	}
	if m.SrcTimestamp != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.SrcTimestamp))
		i--
		dAtA[i] = 0x28
	}
	if len(m.SrcTxHash) > 0 {
		i -= len(m.SrcTxHash)
		copy(dAtA[i:], m.SrcTxHash)
		i = encodeVarintTx(dAtA, i, uint64(len(m.SrcTxHash)))
		i--
		dAtA[i] = 0x22
	}
	if m.SrcChainType != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.SrcChainType))
		i--
		dAtA[i] = 0x18
	}
	if len(m.SrcChainId) > 0 {
		i -= len(m.SrcChainId)
		copy(dAtA[i:], m.SrcChainId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.SrcChainId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Orchestrator) > 0 {
		i -= len(m.Orchestrator)
		copy(dAtA[i:], m.Orchestrator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Orchestrator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgFundsDepositedResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgFundsDepositedResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgFundsDepositedResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgFundsDeposited) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Orchestrator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.SrcChainId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.SrcChainType != 0 {
		n += 1 + sovTx(uint64(m.SrcChainType))
	}
	l = len(m.SrcTxHash)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.SrcTimestamp != 0 {
		n += 1 + sovTx(uint64(m.SrcTimestamp))
	}
	l = len(m.Contract)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.DepositId != 0 {
		n += 1 + sovTx(uint64(m.DepositId))
	}
	if m.BlockHeight != 0 {
		n += 1 + sovTx(uint64(m.BlockHeight))
	}
	l = len(m.DestChainId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.DestChainType != 0 {
		n += 1 + sovTx(uint64(m.DestChainType))
	}
	if m.Amount != 0 {
		n += 1 + sovTx(uint64(m.Amount))
	}
	if m.RelayerFees != 0 {
		n += 1 + sovTx(uint64(m.RelayerFees))
	}
	l = len(m.SrcToken)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Recipient)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Depositor)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgFundsDepositedResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgFundsDeposited) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgFundsDeposited: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgFundsDeposited: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Orchestrator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Orchestrator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SrcChainId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SrcChainId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SrcChainType", wireType)
			}
			m.SrcChainType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SrcChainType |= types.ChainType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SrcTxHash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SrcTxHash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SrcTimestamp", wireType)
			}
			m.SrcTimestamp = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SrcTimestamp |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Contract", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Contract = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DepositId", wireType)
			}
			m.DepositId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DepositId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlockHeight", wireType)
			}
			m.BlockHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BlockHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DestChainId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DestChainId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DestChainType", wireType)
			}
			m.DestChainType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DestChainType |= types.ChainType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			m.Amount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Amount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 12:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RelayerFees", wireType)
			}
			m.RelayerFees = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RelayerFees |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 13:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SrcToken", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SrcToken = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 14:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Recipient", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Recipient = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 15:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Depositor", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Depositor = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgFundsDepositedResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgFundsDepositedResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgFundsDepositedResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
