// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: inbound/incoming_tx.proto

package types

import (
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	types1 "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	types "github.com/router-protocol/sdk-go/routerchain/multichain/types"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type IncomingTx struct {
	ChainType            types.ChainType                        `protobuf:"varint,1,opt,name=chainType,proto3,enum=routerprotocol.routerchain.multichain.ChainType" json:"chainType,omitempty"`
	ChainId              string                                 `protobuf:"bytes,2,opt,name=chainId,proto3" json:"chainId,omitempty"`
	EventNonce           uint64                                 `protobuf:"varint,3,opt,name=eventNonce,proto3" json:"eventNonce,omitempty"`
	BlockHeight          uint64                                 `protobuf:"varint,4,opt,name=blockHeight,proto3" json:"blockHeight,omitempty"`
	SourceTxHash         string                                 `protobuf:"bytes,5,opt,name=sourceTxHash,proto3" json:"sourceTxHash,omitempty"`
	SourceTimestamp      uint64                                 `protobuf:"varint,6,opt,name=sourceTimestamp,proto3" json:"sourceTimestamp,omitempty"`
	SourceSender         []byte                                 `protobuf:"bytes,7,opt,name=sourceSender,proto3" json:"sourceSender,omitempty"`
	TxOrigin             string                                 `protobuf:"bytes,8,opt,name=txOrigin,proto3" json:"txOrigin,omitempty"`
	RouterBridgeContract string                                 `protobuf:"bytes,9,opt,name=routerBridgeContract,proto3" json:"routerBridgeContract,omitempty"`
	Payload              []byte                                 `protobuf:"bytes,10,opt,name=payload,proto3" json:"payload,omitempty"`
	GasLimit             uint64                                 `protobuf:"varint,11,opt,name=gasLimit,proto3" json:"gasLimit,omitempty"`
	TxFeeInRoute         types1.Coin                            `protobuf:"bytes,12,opt,name=txFeeInRoute,proto3" json:"txFeeInRoute"`
	FeePayer             string                                 `protobuf:"bytes,13,opt,name=feePayer,proto3" json:"feePayer,omitempty"`
	RouteAmount          github_com_cosmos_cosmos_sdk_types.Int `protobuf:"bytes,14,opt,name=routeAmount,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Int" json:"routeAmount"`
	RouteRecipient       string                                 `protobuf:"bytes,15,opt,name=routeRecipient,proto3" json:"routeRecipient,omitempty"`
	AsmAddress           []byte                                 `protobuf:"bytes,16,opt,name=asmAddress,proto3" json:"asmAddress,omitempty"`
	Status               IncomingTxStatus                       `protobuf:"varint,17,opt,name=status,proto3,enum=routerprotocol.routerchain.inbound.IncomingTxStatus" json:"status,omitempty"`
}

func (m *IncomingTx) Reset()         { *m = IncomingTx{} }
func (m *IncomingTx) String() string { return proto.CompactTextString(m) }
func (*IncomingTx) ProtoMessage()    {}
func (*IncomingTx) Descriptor() ([]byte, []int) {
	return fileDescriptor_a8ee1d07fc6f736f, []int{0}
}
func (m *IncomingTx) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *IncomingTx) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_IncomingTx.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *IncomingTx) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IncomingTx.Merge(m, src)
}
func (m *IncomingTx) XXX_Size() int {
	return m.Size()
}
func (m *IncomingTx) XXX_DiscardUnknown() {
	xxx_messageInfo_IncomingTx.DiscardUnknown(m)
}

var xxx_messageInfo_IncomingTx proto.InternalMessageInfo

func (m *IncomingTx) GetChainType() types.ChainType {
	if m != nil {
		return m.ChainType
	}
	return types.CHAIN_TYPE_NONE
}

func (m *IncomingTx) GetChainId() string {
	if m != nil {
		return m.ChainId
	}
	return ""
}

func (m *IncomingTx) GetEventNonce() uint64 {
	if m != nil {
		return m.EventNonce
	}
	return 0
}

func (m *IncomingTx) GetBlockHeight() uint64 {
	if m != nil {
		return m.BlockHeight
	}
	return 0
}

func (m *IncomingTx) GetSourceTxHash() string {
	if m != nil {
		return m.SourceTxHash
	}
	return ""
}

func (m *IncomingTx) GetSourceTimestamp() uint64 {
	if m != nil {
		return m.SourceTimestamp
	}
	return 0
}

func (m *IncomingTx) GetSourceSender() []byte {
	if m != nil {
		return m.SourceSender
	}
	return nil
}

func (m *IncomingTx) GetTxOrigin() string {
	if m != nil {
		return m.TxOrigin
	}
	return ""
}

func (m *IncomingTx) GetRouterBridgeContract() string {
	if m != nil {
		return m.RouterBridgeContract
	}
	return ""
}

func (m *IncomingTx) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *IncomingTx) GetGasLimit() uint64 {
	if m != nil {
		return m.GasLimit
	}
	return 0
}

func (m *IncomingTx) GetTxFeeInRoute() types1.Coin {
	if m != nil {
		return m.TxFeeInRoute
	}
	return types1.Coin{}
}

func (m *IncomingTx) GetFeePayer() string {
	if m != nil {
		return m.FeePayer
	}
	return ""
}

func (m *IncomingTx) GetRouteRecipient() string {
	if m != nil {
		return m.RouteRecipient
	}
	return ""
}

func (m *IncomingTx) GetAsmAddress() []byte {
	if m != nil {
		return m.AsmAddress
	}
	return nil
}

func (m *IncomingTx) GetStatus() IncomingTxStatus {
	if m != nil {
		return m.Status
	}
	return INCOMING_TX_CREATED
}

type InboundRequestClaimHash struct {
	ChainType            types.ChainType                        `protobuf:"varint,1,opt,name=chainType,proto3,enum=routerprotocol.routerchain.multichain.ChainType" json:"chainType,omitempty"`
	ChainId              string                                 `protobuf:"bytes,2,opt,name=chainId,proto3" json:"chainId,omitempty"`
	EventNonce           uint64                                 `protobuf:"varint,3,opt,name=eventNonce,proto3" json:"eventNonce,omitempty"`
	BlockHeight          uint64                                 `protobuf:"varint,4,opt,name=blockHeight,proto3" json:"blockHeight,omitempty"`
	SourceTxHash         string                                 `protobuf:"bytes,5,opt,name=sourceTxHash,proto3" json:"sourceTxHash,omitempty"`
	SourceTimestamp      uint64                                 `protobuf:"varint,6,opt,name=sourceTimestamp,proto3" json:"sourceTimestamp,omitempty"`
	SourceSender         []byte                                 `protobuf:"bytes,7,opt,name=sourceSender,proto3" json:"sourceSender,omitempty"`
	TxOrigin             string                                 `protobuf:"bytes,8,opt,name=txOrigin,proto3" json:"txOrigin,omitempty"`
	RouterBridgeContract string                                 `protobuf:"bytes,9,opt,name=routerBridgeContract,proto3" json:"routerBridgeContract,omitempty"`
	Payload              []byte                                 `protobuf:"bytes,10,opt,name=payload,proto3" json:"payload,omitempty"`
	GasLimit             uint64                                 `protobuf:"varint,11,opt,name=gasLimit,proto3" json:"gasLimit,omitempty"`
	RouteAmount          github_com_cosmos_cosmos_sdk_types.Int `protobuf:"bytes,12,opt,name=routeAmount,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Int" json:"routeAmount"`
	RouteRecipient       string                                 `protobuf:"bytes,13,opt,name=routeRecipient,proto3" json:"routeRecipient,omitempty"`
	AsmAddress           []byte                                 `protobuf:"bytes,14,opt,name=asmAddress,proto3" json:"asmAddress,omitempty"`
}

func (m *InboundRequestClaimHash) Reset()         { *m = InboundRequestClaimHash{} }
func (m *InboundRequestClaimHash) String() string { return proto.CompactTextString(m) }
func (*InboundRequestClaimHash) ProtoMessage()    {}
func (*InboundRequestClaimHash) Descriptor() ([]byte, []int) {
	return fileDescriptor_a8ee1d07fc6f736f, []int{1}
}
func (m *InboundRequestClaimHash) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *InboundRequestClaimHash) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_InboundRequestClaimHash.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *InboundRequestClaimHash) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InboundRequestClaimHash.Merge(m, src)
}
func (m *InboundRequestClaimHash) XXX_Size() int {
	return m.Size()
}
func (m *InboundRequestClaimHash) XXX_DiscardUnknown() {
	xxx_messageInfo_InboundRequestClaimHash.DiscardUnknown(m)
}

var xxx_messageInfo_InboundRequestClaimHash proto.InternalMessageInfo

func (m *InboundRequestClaimHash) GetChainType() types.ChainType {
	if m != nil {
		return m.ChainType
	}
	return types.CHAIN_TYPE_NONE
}

func (m *InboundRequestClaimHash) GetChainId() string {
	if m != nil {
		return m.ChainId
	}
	return ""
}

func (m *InboundRequestClaimHash) GetEventNonce() uint64 {
	if m != nil {
		return m.EventNonce
	}
	return 0
}

func (m *InboundRequestClaimHash) GetBlockHeight() uint64 {
	if m != nil {
		return m.BlockHeight
	}
	return 0
}

func (m *InboundRequestClaimHash) GetSourceTxHash() string {
	if m != nil {
		return m.SourceTxHash
	}
	return ""
}

func (m *InboundRequestClaimHash) GetSourceTimestamp() uint64 {
	if m != nil {
		return m.SourceTimestamp
	}
	return 0
}

func (m *InboundRequestClaimHash) GetSourceSender() []byte {
	if m != nil {
		return m.SourceSender
	}
	return nil
}

func (m *InboundRequestClaimHash) GetTxOrigin() string {
	if m != nil {
		return m.TxOrigin
	}
	return ""
}

func (m *InboundRequestClaimHash) GetRouterBridgeContract() string {
	if m != nil {
		return m.RouterBridgeContract
	}
	return ""
}

func (m *InboundRequestClaimHash) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *InboundRequestClaimHash) GetGasLimit() uint64 {
	if m != nil {
		return m.GasLimit
	}
	return 0
}

func (m *InboundRequestClaimHash) GetRouteRecipient() string {
	if m != nil {
		return m.RouteRecipient
	}
	return ""
}

func (m *InboundRequestClaimHash) GetAsmAddress() []byte {
	if m != nil {
		return m.AsmAddress
	}
	return nil
}

func init() {
	proto.RegisterType((*IncomingTx)(nil), "routerprotocol.routerchain.inbound.IncomingTx")
	proto.RegisterType((*InboundRequestClaimHash)(nil), "routerprotocol.routerchain.inbound.InboundRequestClaimHash")
}

func init() { proto.RegisterFile("inbound/incoming_tx.proto", fileDescriptor_a8ee1d07fc6f736f) }

var fileDescriptor_a8ee1d07fc6f736f = []byte{
	// 612 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x55, 0x4f, 0x4f, 0xdb, 0x4e,
	0x10, 0x8d, 0x7f, 0xbf, 0xf0, 0x6f, 0x13, 0x42, 0xbb, 0x42, 0xea, 0x42, 0x25, 0x63, 0xe5, 0x80,
	0x72, 0x61, 0x5d, 0x68, 0xa5, 0x9e, 0x49, 0xa4, 0x8a, 0x48, 0x88, 0x52, 0xc3, 0xa9, 0x17, 0xb4,
	0xb6, 0xa7, 0xce, 0x8a, 0x78, 0xd7, 0xf5, 0xae, 0x91, 0xf3, 0x2d, 0xfa, 0xb1, 0x38, 0x72, 0x6b,
	0xd5, 0x03, 0xaa, 0xe0, 0x53, 0xf4, 0x56, 0x79, 0x6d, 0x93, 0x3f, 0x42, 0x6d, 0x2f, 0x95, 0x7a,
	0xe8, 0x25, 0xf1, 0x7b, 0x3b, 0xf3, 0x66, 0x32, 0xfb, 0x26, 0x46, 0x5b, 0x5c, 0xf8, 0x32, 0x13,
	0xa1, 0xcb, 0x45, 0x20, 0x63, 0x2e, 0xa2, 0x0b, 0x9d, 0xd3, 0x24, 0x95, 0x5a, 0xe2, 0x6e, 0x2a,
	0x33, 0x0d, 0xa9, 0x01, 0x81, 0x1c, 0xd3, 0x12, 0x06, 0x23, 0xc6, 0x05, 0xad, 0xb2, 0xb6, 0x9d,
	0x47, 0xd2, 0x2f, 0x94, 0x66, 0x3a, 0x53, 0xa5, 0xca, 0xf6, 0xf3, 0x38, 0x1b, 0x6b, 0x6e, 0xb2,
	0x5c, 0xf3, 0x79, 0xa1, 0x27, 0x09, 0x54, 0x87, 0x76, 0x20, 0x55, 0x2c, 0x95, 0xeb, 0x33, 0x05,
	0xee, 0xd5, 0xbe, 0x0f, 0x9a, 0xed, 0xbb, 0x81, 0xe4, 0xa2, 0x3a, 0xdf, 0x8c, 0x64, 0x24, 0xcd,
	0xa3, 0x5b, 0x3c, 0x95, 0x6c, 0xf7, 0xfb, 0x12, 0x42, 0xc3, 0xaa, 0xde, 0x79, 0x8e, 0x4f, 0xd0,
	0x9a, 0x11, 0x3e, 0x9f, 0x24, 0x40, 0x2c, 0xc7, 0xea, 0x75, 0x0e, 0x5e, 0xd0, 0x9f, 0xf4, 0x3e,
	0x6d, 0x88, 0x0e, 0xea, 0x3c, 0x6f, 0x2a, 0x81, 0x09, 0x5a, 0x31, 0x60, 0x18, 0x92, 0xff, 0x1c,
	0xab, 0xb7, 0xe6, 0xd5, 0x10, 0xdb, 0x08, 0xc1, 0x15, 0x08, 0x7d, 0x22, 0x45, 0x00, 0xe4, 0x7f,
	0xc7, 0xea, 0x35, 0xbd, 0x19, 0x06, 0x3b, 0xa8, 0xe5, 0x8f, 0x65, 0x70, 0x79, 0x04, 0x3c, 0x1a,
	0x69, 0xd2, 0x34, 0x01, 0xb3, 0x14, 0xee, 0xa2, 0xb6, 0x92, 0x59, 0x1a, 0xc0, 0x79, 0x7e, 0xc4,
	0xd4, 0x88, 0x2c, 0x99, 0x02, 0x73, 0x1c, 0xee, 0xa1, 0x8d, 0x0a, 0xf3, 0x18, 0x94, 0x66, 0x71,
	0x42, 0x96, 0x8d, 0xd2, 0x22, 0x3d, 0x55, 0x3b, 0x03, 0x11, 0x42, 0x4a, 0x56, 0x1c, 0xab, 0xd7,
	0xf6, 0xe6, 0x38, 0xbc, 0x8d, 0x56, 0x75, 0xfe, 0x36, 0xe5, 0x11, 0x17, 0x64, 0xd5, 0x54, 0x7b,
	0xc0, 0xf8, 0x00, 0x6d, 0x96, 0x83, 0xe9, 0xa7, 0x3c, 0x8c, 0x60, 0x20, 0x85, 0x4e, 0x59, 0xa0,
	0xc9, 0x9a, 0x89, 0x7b, 0xf4, 0xac, 0x98, 0x4e, 0xc2, 0x26, 0x63, 0xc9, 0x42, 0x82, 0x4c, 0xb9,
	0x1a, 0x16, 0x95, 0x22, 0xa6, 0x8e, 0x79, 0xcc, 0x35, 0x69, 0x99, 0x86, 0x1f, 0x30, 0x1e, 0xa0,
	0xb6, 0xce, 0xdf, 0x00, 0x0c, 0x85, 0x57, 0x88, 0x92, 0xb6, 0x63, 0xf5, 0x5a, 0x07, 0x5b, 0xb4,
	0xbc, 0x7f, 0x5a, 0xdc, 0x3f, 0xad, 0xee, 0x9f, 0x0e, 0x24, 0x17, 0xfd, 0xe6, 0xf5, 0xed, 0x4e,
	0xc3, 0x9b, 0x4b, 0x2a, 0x0a, 0x7c, 0x00, 0x38, 0x65, 0x13, 0x48, 0xc9, 0x7a, 0xf9, 0x53, 0x6a,
	0x8c, 0x4f, 0x51, 0xcb, 0xb4, 0x7b, 0x18, 0xcb, 0x4c, 0x68, 0xd2, 0x29, 0x8e, 0xfb, 0xb4, 0x10,
	0xf9, 0x7a, 0xbb, 0xb3, 0x1b, 0x71, 0x3d, 0xca, 0x7c, 0x1a, 0xc8, 0xd8, 0xad, 0x1c, 0x57, 0x7e,
	0xed, 0xa9, 0xf0, 0xd2, 0x2d, 0xfc, 0xa8, 0xe8, 0x50, 0x68, 0x6f, 0x56, 0x02, 0xef, 0xa2, 0x8e,
	0x81, 0x1e, 0x04, 0x3c, 0xe1, 0x20, 0x34, 0xd9, 0x30, 0x35, 0x17, 0xd8, 0xc2, 0x14, 0x4c, 0xc5,
	0x87, 0x61, 0x98, 0x82, 0x52, 0xe4, 0x89, 0x99, 0xc9, 0x0c, 0x83, 0x8f, 0xd1, 0x72, 0xb9, 0x10,
	0xe4, 0xa9, 0xf1, 0xe6, 0x2b, 0xfa, 0xeb, 0xbd, 0xa2, 0x53, 0x7b, 0x9f, 0x99, 0x5c, 0xaf, 0xd2,
	0xe8, 0x7e, 0x6e, 0xa2, 0x67, 0xc3, 0x32, 0xc8, 0x83, 0x8f, 0x19, 0x28, 0x3d, 0x18, 0x33, 0x1e,
	0x1b, 0xe3, 0xfc, 0x5b, 0x84, 0xbf, 0x7f, 0x11, 0x16, 0x7c, 0xda, 0xfe, 0x13, 0x3e, 0x5d, 0xff,
	0x0d, 0x9f, 0x76, 0x16, 0x7d, 0xda, 0x7f, 0x77, 0x7d, 0x67, 0x5b, 0x37, 0x77, 0xb6, 0xf5, 0xed,
	0xce, 0xb6, 0x3e, 0xdd, 0xdb, 0x8d, 0x9b, 0x7b, 0xbb, 0xf1, 0xe5, 0xde, 0x6e, 0xbc, 0x7f, 0x3d,
	0xd3, 0x56, 0x39, 0x8a, 0xbd, 0xda, 0x4f, 0x35, 0x2e, 0xff, 0xdf, 0x73, 0xb7, 0x7e, 0x1d, 0x98,
	0x5e, 0xfd, 0x65, 0x13, 0xf6, 0xf2, 0x47, 0x00, 0x00, 0x00, 0xff, 0xff, 0xe8, 0x1c, 0xbc, 0xb9,
	0x65, 0x06, 0x00, 0x00,
}

func (m *IncomingTx) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *IncomingTx) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *IncomingTx) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Status != 0 {
		i = encodeVarintIncomingTx(dAtA, i, uint64(m.Status))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x88
	}
	if len(m.AsmAddress) > 0 {
		i -= len(m.AsmAddress)
		copy(dAtA[i:], m.AsmAddress)
		i = encodeVarintIncomingTx(dAtA, i, uint64(len(m.AsmAddress)))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x82
	}
	if len(m.RouteRecipient) > 0 {
		i -= len(m.RouteRecipient)
		copy(dAtA[i:], m.RouteRecipient)
		i = encodeVarintIncomingTx(dAtA, i, uint64(len(m.RouteRecipient)))
		i--
		dAtA[i] = 0x7a
	}
	{
		size := m.RouteAmount.Size()
		i -= size
		if _, err := m.RouteAmount.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintIncomingTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x72
	if len(m.FeePayer) > 0 {
		i -= len(m.FeePayer)
		copy(dAtA[i:], m.FeePayer)
		i = encodeVarintIncomingTx(dAtA, i, uint64(len(m.FeePayer)))
		i--
		dAtA[i] = 0x6a
	}
	{
		size, err := m.TxFeeInRoute.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintIncomingTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x62
	if m.GasLimit != 0 {
		i = encodeVarintIncomingTx(dAtA, i, uint64(m.GasLimit))
		i--
		dAtA[i] = 0x58
	}
	if len(m.Payload) > 0 {
		i -= len(m.Payload)
		copy(dAtA[i:], m.Payload)
		i = encodeVarintIncomingTx(dAtA, i, uint64(len(m.Payload)))
		i--
		dAtA[i] = 0x52
	}
	if len(m.RouterBridgeContract) > 0 {
		i -= len(m.RouterBridgeContract)
		copy(dAtA[i:], m.RouterBridgeContract)
		i = encodeVarintIncomingTx(dAtA, i, uint64(len(m.RouterBridgeContract)))
		i--
		dAtA[i] = 0x4a
	}
	if len(m.TxOrigin) > 0 {
		i -= len(m.TxOrigin)
		copy(dAtA[i:], m.TxOrigin)
		i = encodeVarintIncomingTx(dAtA, i, uint64(len(m.TxOrigin)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.SourceSender) > 0 {
		i -= len(m.SourceSender)
		copy(dAtA[i:], m.SourceSender)
		i = encodeVarintIncomingTx(dAtA, i, uint64(len(m.SourceSender)))
		i--
		dAtA[i] = 0x3a
	}
	if m.SourceTimestamp != 0 {
		i = encodeVarintIncomingTx(dAtA, i, uint64(m.SourceTimestamp))
		i--
		dAtA[i] = 0x30
	}
	if len(m.SourceTxHash) > 0 {
		i -= len(m.SourceTxHash)
		copy(dAtA[i:], m.SourceTxHash)
		i = encodeVarintIncomingTx(dAtA, i, uint64(len(m.SourceTxHash)))
		i--
		dAtA[i] = 0x2a
	}
	if m.BlockHeight != 0 {
		i = encodeVarintIncomingTx(dAtA, i, uint64(m.BlockHeight))
		i--
		dAtA[i] = 0x20
	}
	if m.EventNonce != 0 {
		i = encodeVarintIncomingTx(dAtA, i, uint64(m.EventNonce))
		i--
		dAtA[i] = 0x18
	}
	if len(m.ChainId) > 0 {
		i -= len(m.ChainId)
		copy(dAtA[i:], m.ChainId)
		i = encodeVarintIncomingTx(dAtA, i, uint64(len(m.ChainId)))
		i--
		dAtA[i] = 0x12
	}
	if m.ChainType != 0 {
		i = encodeVarintIncomingTx(dAtA, i, uint64(m.ChainType))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *InboundRequestClaimHash) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *InboundRequestClaimHash) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *InboundRequestClaimHash) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.AsmAddress) > 0 {
		i -= len(m.AsmAddress)
		copy(dAtA[i:], m.AsmAddress)
		i = encodeVarintIncomingTx(dAtA, i, uint64(len(m.AsmAddress)))
		i--
		dAtA[i] = 0x72
	}
	if len(m.RouteRecipient) > 0 {
		i -= len(m.RouteRecipient)
		copy(dAtA[i:], m.RouteRecipient)
		i = encodeVarintIncomingTx(dAtA, i, uint64(len(m.RouteRecipient)))
		i--
		dAtA[i] = 0x6a
	}
	{
		size := m.RouteAmount.Size()
		i -= size
		if _, err := m.RouteAmount.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintIncomingTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x62
	if m.GasLimit != 0 {
		i = encodeVarintIncomingTx(dAtA, i, uint64(m.GasLimit))
		i--
		dAtA[i] = 0x58
	}
	if len(m.Payload) > 0 {
		i -= len(m.Payload)
		copy(dAtA[i:], m.Payload)
		i = encodeVarintIncomingTx(dAtA, i, uint64(len(m.Payload)))
		i--
		dAtA[i] = 0x52
	}
	if len(m.RouterBridgeContract) > 0 {
		i -= len(m.RouterBridgeContract)
		copy(dAtA[i:], m.RouterBridgeContract)
		i = encodeVarintIncomingTx(dAtA, i, uint64(len(m.RouterBridgeContract)))
		i--
		dAtA[i] = 0x4a
	}
	if len(m.TxOrigin) > 0 {
		i -= len(m.TxOrigin)
		copy(dAtA[i:], m.TxOrigin)
		i = encodeVarintIncomingTx(dAtA, i, uint64(len(m.TxOrigin)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.SourceSender) > 0 {
		i -= len(m.SourceSender)
		copy(dAtA[i:], m.SourceSender)
		i = encodeVarintIncomingTx(dAtA, i, uint64(len(m.SourceSender)))
		i--
		dAtA[i] = 0x3a
	}
	if m.SourceTimestamp != 0 {
		i = encodeVarintIncomingTx(dAtA, i, uint64(m.SourceTimestamp))
		i--
		dAtA[i] = 0x30
	}
	if len(m.SourceTxHash) > 0 {
		i -= len(m.SourceTxHash)
		copy(dAtA[i:], m.SourceTxHash)
		i = encodeVarintIncomingTx(dAtA, i, uint64(len(m.SourceTxHash)))
		i--
		dAtA[i] = 0x2a
	}
	if m.BlockHeight != 0 {
		i = encodeVarintIncomingTx(dAtA, i, uint64(m.BlockHeight))
		i--
		dAtA[i] = 0x20
	}
	if m.EventNonce != 0 {
		i = encodeVarintIncomingTx(dAtA, i, uint64(m.EventNonce))
		i--
		dAtA[i] = 0x18
	}
	if len(m.ChainId) > 0 {
		i -= len(m.ChainId)
		copy(dAtA[i:], m.ChainId)
		i = encodeVarintIncomingTx(dAtA, i, uint64(len(m.ChainId)))
		i--
		dAtA[i] = 0x12
	}
	if m.ChainType != 0 {
		i = encodeVarintIncomingTx(dAtA, i, uint64(m.ChainType))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintIncomingTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovIncomingTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *IncomingTx) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ChainType != 0 {
		n += 1 + sovIncomingTx(uint64(m.ChainType))
	}
	l = len(m.ChainId)
	if l > 0 {
		n += 1 + l + sovIncomingTx(uint64(l))
	}
	if m.EventNonce != 0 {
		n += 1 + sovIncomingTx(uint64(m.EventNonce))
	}
	if m.BlockHeight != 0 {
		n += 1 + sovIncomingTx(uint64(m.BlockHeight))
	}
	l = len(m.SourceTxHash)
	if l > 0 {
		n += 1 + l + sovIncomingTx(uint64(l))
	}
	if m.SourceTimestamp != 0 {
		n += 1 + sovIncomingTx(uint64(m.SourceTimestamp))
	}
	l = len(m.SourceSender)
	if l > 0 {
		n += 1 + l + sovIncomingTx(uint64(l))
	}
	l = len(m.TxOrigin)
	if l > 0 {
		n += 1 + l + sovIncomingTx(uint64(l))
	}
	l = len(m.RouterBridgeContract)
	if l > 0 {
		n += 1 + l + sovIncomingTx(uint64(l))
	}
	l = len(m.Payload)
	if l > 0 {
		n += 1 + l + sovIncomingTx(uint64(l))
	}
	if m.GasLimit != 0 {
		n += 1 + sovIncomingTx(uint64(m.GasLimit))
	}
	l = m.TxFeeInRoute.Size()
	n += 1 + l + sovIncomingTx(uint64(l))
	l = len(m.FeePayer)
	if l > 0 {
		n += 1 + l + sovIncomingTx(uint64(l))
	}
	l = m.RouteAmount.Size()
	n += 1 + l + sovIncomingTx(uint64(l))
	l = len(m.RouteRecipient)
	if l > 0 {
		n += 1 + l + sovIncomingTx(uint64(l))
	}
	l = len(m.AsmAddress)
	if l > 0 {
		n += 2 + l + sovIncomingTx(uint64(l))
	}
	if m.Status != 0 {
		n += 2 + sovIncomingTx(uint64(m.Status))
	}
	return n
}

func (m *InboundRequestClaimHash) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ChainType != 0 {
		n += 1 + sovIncomingTx(uint64(m.ChainType))
	}
	l = len(m.ChainId)
	if l > 0 {
		n += 1 + l + sovIncomingTx(uint64(l))
	}
	if m.EventNonce != 0 {
		n += 1 + sovIncomingTx(uint64(m.EventNonce))
	}
	if m.BlockHeight != 0 {
		n += 1 + sovIncomingTx(uint64(m.BlockHeight))
	}
	l = len(m.SourceTxHash)
	if l > 0 {
		n += 1 + l + sovIncomingTx(uint64(l))
	}
	if m.SourceTimestamp != 0 {
		n += 1 + sovIncomingTx(uint64(m.SourceTimestamp))
	}
	l = len(m.SourceSender)
	if l > 0 {
		n += 1 + l + sovIncomingTx(uint64(l))
	}
	l = len(m.TxOrigin)
	if l > 0 {
		n += 1 + l + sovIncomingTx(uint64(l))
	}
	l = len(m.RouterBridgeContract)
	if l > 0 {
		n += 1 + l + sovIncomingTx(uint64(l))
	}
	l = len(m.Payload)
	if l > 0 {
		n += 1 + l + sovIncomingTx(uint64(l))
	}
	if m.GasLimit != 0 {
		n += 1 + sovIncomingTx(uint64(m.GasLimit))
	}
	l = m.RouteAmount.Size()
	n += 1 + l + sovIncomingTx(uint64(l))
	l = len(m.RouteRecipient)
	if l > 0 {
		n += 1 + l + sovIncomingTx(uint64(l))
	}
	l = len(m.AsmAddress)
	if l > 0 {
		n += 1 + l + sovIncomingTx(uint64(l))
	}
	return n
}

func sovIncomingTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozIncomingTx(x uint64) (n int) {
	return sovIncomingTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *IncomingTx) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowIncomingTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: IncomingTx: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: IncomingTx: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChainType", wireType)
			}
			m.ChainType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIncomingTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ChainType |= types.ChainType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChainId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIncomingTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthIncomingTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthIncomingTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ChainId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EventNonce", wireType)
			}
			m.EventNonce = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIncomingTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EventNonce |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlockHeight", wireType)
			}
			m.BlockHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIncomingTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BlockHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SourceTxHash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIncomingTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthIncomingTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthIncomingTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SourceTxHash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SourceTimestamp", wireType)
			}
			m.SourceTimestamp = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIncomingTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SourceTimestamp |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SourceSender", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIncomingTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthIncomingTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthIncomingTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SourceSender = append(m.SourceSender[:0], dAtA[iNdEx:postIndex]...)
			if m.SourceSender == nil {
				m.SourceSender = []byte{}
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TxOrigin", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIncomingTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthIncomingTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthIncomingTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TxOrigin = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RouterBridgeContract", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIncomingTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthIncomingTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthIncomingTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RouterBridgeContract = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Payload", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIncomingTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthIncomingTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthIncomingTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Payload = append(m.Payload[:0], dAtA[iNdEx:postIndex]...)
			if m.Payload == nil {
				m.Payload = []byte{}
			}
			iNdEx = postIndex
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field GasLimit", wireType)
			}
			m.GasLimit = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIncomingTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.GasLimit |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TxFeeInRoute", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIncomingTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthIncomingTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthIncomingTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TxFeeInRoute.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 13:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FeePayer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIncomingTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthIncomingTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthIncomingTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FeePayer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 14:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RouteAmount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIncomingTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthIncomingTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthIncomingTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.RouteAmount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 15:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RouteRecipient", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIncomingTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthIncomingTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthIncomingTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RouteRecipient = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 16:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AsmAddress", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIncomingTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthIncomingTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthIncomingTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AsmAddress = append(m.AsmAddress[:0], dAtA[iNdEx:postIndex]...)
			if m.AsmAddress == nil {
				m.AsmAddress = []byte{}
			}
			iNdEx = postIndex
		case 17:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIncomingTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= IncomingTxStatus(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipIncomingTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthIncomingTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *InboundRequestClaimHash) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowIncomingTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: InboundRequestClaimHash: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: InboundRequestClaimHash: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChainType", wireType)
			}
			m.ChainType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIncomingTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ChainType |= types.ChainType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChainId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIncomingTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthIncomingTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthIncomingTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ChainId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EventNonce", wireType)
			}
			m.EventNonce = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIncomingTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EventNonce |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlockHeight", wireType)
			}
			m.BlockHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIncomingTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BlockHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SourceTxHash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIncomingTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthIncomingTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthIncomingTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SourceTxHash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SourceTimestamp", wireType)
			}
			m.SourceTimestamp = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIncomingTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SourceTimestamp |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SourceSender", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIncomingTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthIncomingTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthIncomingTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SourceSender = append(m.SourceSender[:0], dAtA[iNdEx:postIndex]...)
			if m.SourceSender == nil {
				m.SourceSender = []byte{}
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TxOrigin", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIncomingTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthIncomingTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthIncomingTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TxOrigin = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RouterBridgeContract", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIncomingTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthIncomingTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthIncomingTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RouterBridgeContract = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Payload", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIncomingTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthIncomingTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthIncomingTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Payload = append(m.Payload[:0], dAtA[iNdEx:postIndex]...)
			if m.Payload == nil {
				m.Payload = []byte{}
			}
			iNdEx = postIndex
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field GasLimit", wireType)
			}
			m.GasLimit = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIncomingTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.GasLimit |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RouteAmount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIncomingTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthIncomingTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthIncomingTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.RouteAmount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 13:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RouteRecipient", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIncomingTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthIncomingTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthIncomingTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RouteRecipient = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 14:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AsmAddress", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIncomingTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthIncomingTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthIncomingTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AsmAddress = append(m.AsmAddress[:0], dAtA[iNdEx:postIndex]...)
			if m.AsmAddress == nil {
				m.AsmAddress = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipIncomingTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthIncomingTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipIncomingTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowIncomingTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowIncomingTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowIncomingTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthIncomingTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupIncomingTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthIncomingTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthIncomingTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowIncomingTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupIncomingTx = fmt.Errorf("proto: unexpected end of group")
)
